#! /bin/sh

# Start the hotkey daemon.
sxhkd &

# Start dunst.
dunst -config /home/favre49/.config/dunst/dunstrc &

# Start the compositor
picom --config /home/favre49/.config/picom.conf &

# Set the wallpaper with feh.
~/.fehbg &

# Start polybar.
/home/favre49/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

