#! /bin/sh

# Start the hotkey daemon.
sxhkd &

# Set up the monitor
/home/favre49/.scripts/start_monitor.sh

# Start dunst.
dunst -config /home/favre49/.config/dunst/dunstrc &

# Start the compositor
picom --config /home/favre49/.config/picom.conf &

# Set the wallpaper with feh.
~/.fehbg &

# Setup workspaces
bspc monitor eDP1 -d I II III IV
bspc monitor HDMI-0 -d V VI VII VIII

# Start polybar.
/home/favre49/.scripts/start_polybar.sh

# >>> Config options <<<<

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

# >>> Rules <<<

bspc rule -a Zathura state=tiled
bspc rule -a spotify desktop=^6
bspc rule -a mail desktop=^5
bspc rule -a news desktop=^8
bspc rule -a qbittorrent desktop=^7



